batch_size: 8
image_shape:
- 256
- 256
learning_rate: 0.0001
log_step: 10
max_ckpts: 3
num_iteration: 160000
resize_size: 512
save_step: 1000
style_dim: 512
style_kernel: 3
style_weight: 100.0
summary_step: 100
