# Basic model parameters
image_shape: [512, 512]
style_dim: 512
style_kernel: 3
style_weight: 200.0

# Groups configuration - choose one approach:
# Option 1: Auto-calculate groups from ratios (default behavior)
groups_ratios: [1.0, 0.5, 0.25, 0.125]
groups: null # Optional, used for fixed groups
groups_list: null # Optional, used for fixed groups

# Training parameters
batch_size: 8
learning_rate: 0.0001
num_iteration: 320000

# Export configuration
fixed_batch_size: 8     # For static computational graph 训练时需要与batch_size一致
use_fixed_size: true    # For static computational graph
dynamic_mode: true      # For dynamic ONNX export

# Logging parameters
log_step: 10
save_step: 100
summary_step: 100
max_ckpts: 3
resize_size: 1024